name: "tj-action changed-files incident"
on: 
  workflow_dispatch:  # Specify when the workflow runs

jobs:
  changed_files:
    runs-on: ubuntu-latest  # Define the runner environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history is available

      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Add repository to safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Debug changed files
        run: echo "Changed files:${{ steps.changed-files.outputs.all_changed_files }}"
